const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Certificate Service
 * Generates PDF ownership certificates with blockchain proof
 */
class CertificateService {
  /**
   * Generate PDF certificate
   */
  async generateCertificate({ title, creatorName, creatorWallet, timestamp, ipfsCid, fingerprintHash, txHash, blockNumber }) {
    return new Promise((resolve, reject) => {
      const certsDir = path.join(__dirname, '../../uploads/certificates');
      if (!fs.existsSync(certsDir)) fs.mkdirSync(certsDir, { recursive: true });

      const fileName = `cert_${Date.now()}.pdf`;
      const filePath = path.join(certsDir, fileName);
      const doc = new PDFDocument({ size: 'A4', margin: 60 });
      const stream = fs.createWriteStream(filePath);

      doc.pipe(stream);

      // ─── Header ────────────────────────────────────
      doc.rect(0, 0, doc.page.width, 120).fill('#0f0f23');
      doc.fontSize(28).fillColor('#00d4ff').text('CREATORCHAIN', 60, 35, { align: 'center' });
      doc.fontSize(12).fillColor('#a0a0b0').text('Certificate of Digital Ownership', 60, 75, { align: 'center' });

      // ─── Decorative line ───────────────────────────
      doc.moveTo(60, 140).lineTo(535, 140).strokeColor('#00d4ff').lineWidth(2).stroke();

      // ─── Title ─────────────────────────────────────
      doc.fillColor('#1a1a2e').fontSize(22).text('Ownership Certificate', 60, 165, { align: 'center' });

      // ─── Content Details ───────────────────────────
      let y = 220;
      const addField = (label, value) => {
        doc.fontSize(10).fillColor('#666').text(label, 60, y);
        doc.fontSize(12).fillColor('#1a1a2e').text(value || 'N/A', 60, y + 15, {
          width: 475,
          lineBreak: true,
        });
        y += 45;
      };

      addField('CONTENT TITLE', title);
      addField('CREATOR', creatorName);
      addField('CREATOR WALLET', creatorWallet);
      addField('REGISTRATION DATE', new Date(timestamp).toLocaleString('en-US', {
        year: 'numeric', month: 'long', day: 'numeric',
        hour: '2-digit', minute: '2-digit', timeZoneName: 'short',
      }));
      addField('IPFS CONTENT ID (CID)', ipfsCid);
      addField('AI FINGERPRINT HASH', fingerprintHash);
      addField('BLOCKCHAIN TX HASH', txHash);
      addField('BLOCK NUMBER', blockNumber?.toString());

      // ─── Verification Box ─────────────────────────
      y += 20;
      doc.rect(60, y, 475, 80).fill('#f0f8ff').stroke('#00d4ff');
      doc.fontSize(10).fillColor('#0066cc').text('🔒 BLOCKCHAIN VERIFIED', 80, y + 15);
      doc.fontSize(9).fillColor('#444').text(
        'This certificate is backed by an immutable blockchain record. ' +
        'The fingerprint hash and ownership data are permanently stored on the Polygon network. ' +
        'Verify by searching the transaction hash on PolygonScan.',
        80, y + 35, { width: 435 }
      );

      // ─── Footer ────────────────────────────────────
      doc.rect(0, doc.page.height - 50, doc.page.width, 50).fill('#0f0f23');
      doc.fontSize(8).fillColor('#a0a0b0').text(
        `Generated by CreatorChain • ${new Date().toISOString()} • Blockchain as Legal Notary`,
        60, doc.page.height - 35, { align: 'center' }
      );

      doc.end();

      stream.on('finish', () => {
        resolve({
          filePath,
          fileName,
          url: `/uploads/certificates/${fileName}`,
        });
      });

      stream.on('error', reject);
    });
  }
}

module.exports = new CertificateService();
